# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-13 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naming', models.CharField(max_length=70)),
            ],
        ),
    ]
